# Generated by Django 6.0 on 2025-12-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_completed_at_alter_task_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Локация'),
        ),
    ]
